In [1]:
import numpy as np
from pore_pressure import eaton_method, Bowers_method, Matthews_Kelly_method

In [2]:
# Define well log values
Vp = np.array([2000, 4000, 5000, 6000])  # compressional wave velocity, m/s
Vs = np.array([1000, 2000, 2500, 3000])  # shear wave velocity, m/s
rho = np.array([2200, 2400, 2500, 2600])  # density, kg/m^3
phi = np.array([0.2, 0.15, 0.1, 0.05])  # porosity

In [3]:
x = Bowers_method(Vp, Vs, rho, phi)
x

array([ 21902.25      ,  38937.33333333,  87609.        , 350436.        ])

In [4]:
y = Matthews_Kelly_method(rho)
y

array([ 5886000., 13734000., 22072500., 31392000.])

In [5]:
z = eaton_method(Vp, Vs, rho, phi)
z

array([ 888888.88888889, 1837837.83783784, 2368421.05263158,
       2923076.92307692])

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

# Load well log data
df = pd.read_csv('well_logs.csv')

# Define input features and target variable
X = df[['resistivity', 'density', 'sonic_velocity', 'gamma_ray', 'lithology', 'facies', 'depth']]
y = df['pore_pressure']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a random forest regressor model
rf = RandomForestRegressor(n_estimators=100, max_depth=10, random_state=42)
rf.fit(X_train, y_train)

# Make predictions on test data
y_pred = rf.predict(X_test)

# Calculate model performance metrics
mae = np.mean(abs(y_test - y_pred))
mse = np.mean((y_test - y_pred) ** 2)
rmse = np.sqrt(mse)
r2 = rf.score(X_test, y_test)

# Make a prediction for new well log data
new_data = pd.DataFrame({'resistivity': [2.5], 'density': [2.3], 'sonic_velocity': [3.5], 'gamma_ray': [40], 'lithology': ['sandstone'], 'facies': ['shale'], 'depth': [2000]})
new_pp = rf.predict(new_data)

print(new_pp)